In [1]:
import ccdm
import numpy as np
from ccdm_initialize import initialize

In [2]:
pOpt = np.array([0.537577302140556,0.322026673986155,0.115556317270981,0.024839706602308])
n = 256
[p_quant,num_info_bits,n_i] = initialize(pOpt,256)


In [3]:
print(p_quant)
print(num_info_bits)
print(n_i)

[0.5390625 0.3203125 0.1171875 0.0234375]
372
[138  82  30   6]


In [4]:
src_symbols = np.random.randint(0, 2, size=num_info_bits)

In [5]:
code_symbols = ccdm.encode(src_symbols, n, n_i)


In [6]:
print(code_symbols)

[2, 1, 1, 1, 3, 3, 2, 1, 1, 3, 4, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 2, 1, 1, 2, 1, 1, 1, 2, 3, 1, 2, 1, 2, 2, 2, 2, 1, 3, 2, 1, 1, 1, 3, 1, 1, 1, 1, 3, 2, 1, 3, 1, 1, 1, 1, 2, 2, 1, 1, 2, 1, 1, 2, 2, 2, 1, 1, 2, 2, 2, 1, 2, 1, 1, 2, 3, 1, 2, 1, 2, 1, 2, 1, 2, 2, 2, 2, 2, 3, 1, 1, 1, 1, 1, 2, 1, 1, 1, 4, 2, 3, 1, 1, 2, 1, 2, 3, 1, 1, 1, 1, 1, 2, 3, 1, 1, 2, 1, 2, 1, 2, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 2, 3, 1, 3, 3, 1, 1, 2, 2, 2, 2, 1, 1, 2, 2, 2, 3, 1, 1, 1, 1, 1, 3, 1, 1, 3, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 2, 1, 2, 2, 2, 1, 2, 1, 1, 2, 2, 1, 1, 1, 1, 2, 1, 2, 2, 2, 1, 1, 1, 2, 1, 3, 3, 3, 1, 1, 3, 1, 1, 2, 1, 4, 1, 2, 3, 2, 1, 1, 2, 2, 1, 1, 1, 2, 3, 1, 1, 2, 2, 2, 2, 1, 4, 1, 1, 1, 3, 2, 1, 4, 1, 2, 1, 3, 1, 2, 4, 1, 2, 2, 1, 3, 3, 1, 1, 1, 2, 3]


In [7]:
len(code_symbols)

256

In [9]:
print(src_symbols)

[1 0 0 1 0 1 1 0 0 1 1 1 0 1 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 1 1 1 1 1 1 1 0
 0 0 0 0 0 1 0 0 1 0 0 0 0 0 1 1 0 1 1 0 0 1 0 0 0 0 0 0 0 1 1 0 0 0 1 1 0
 1 0 0 1 1 0 0 0 0 1 0 1 1 0 0 0 1 0 1 1 0 1 1 1 0 0 1 0 0 0 0 0 1 1 1 1 1
 1 0 1 0 0 1 0 0 1 1 1 0 0 1 1 0 1 0 0 1 1 1 0 1 0 0 1 1 0 1 0 0 1 1 0 0 1
 1 1 1 0 1 0 1 0 1 0 1 1 0 0 0 0 1 1 0 0 1 0 1 1 0 0 0 0 0 1 1 0 0 0 0 1 1
 0 1 0 1 0 0 1 0 0 0 0 1 0 1 1 0 0 1 0 0 1 0 0 0 0 1 0 0 0 1 0 0 1 1 0 1 1
 0 1 1 1 0 0 1 1 0 1 0 0 1 0 0 1 1 1 1 0 0 1 1 0 1 1 0 0 1 1 0 1 1 1 1 0 0
 1 0 0 1 1 1 1 1 1 0 1 1 0 1 1 1 0 1 0 0 1 1 1 0 1 1 0 1 1 0 1 0 1 0 0 0 0
 1 1 0 0 0 0 1 1 0 1 1 0 1 1 0 0 0 1 1 0 1 1 1 1 1 1 0 0 0 0 1 1 1 1 1 1 0
 0 0 1 1 0 1 0 0 0 0 0 1 1 1 1 1 0 1 0 0 1 0 1 1 1 1 0 0 1 0 1 1 0 1 0 1 0
 0 0]


In [10]:
decoded_bits = ccdm.decode(code_symbols, n_i, num_info_bits)
print(decoded_bits)

[1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 

In [12]:
np_src_symbols = np.array(src_symbols)
np_dec_bits = np.array(decoded_bits)
np.array_equal(np_src_symbols, np_dec_bits)

True

In [10]:
pOpt = np.array([0.537577302140556,0.322026673986155,0.115556317270981,0.024839706602308])
n = 256
[p_quant,num_info_bits,n_i] = initialize(pOpt,256)


In [11]:
print(p_quant)
print(num_info_bits)
print(n_i)

[0.5390625 0.3203125 0.1171875 0.0234375]
372
[138  82  30   6]


In [12]:
src_symbols = np.random.randint(0, 2, size=num_info_bits)

In [13]:
code_symbols = ccdm.encode(src_symbols, n, n_i)


In [14]:
print(code_symbols)

[1, 1, 2, 2, 1, 1, 1, 1, 2, 2, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 2, 3, 1, 1, 1, 2, 1, 1, 2, 4, 2, 1, 1, 3, 3, 3, 2, 1, 1, 3, 2, 2, 2, 2, 2, 1, 1, 1, 2, 2, 4, 1, 1, 1, 1, 2, 4, 2, 3, 1, 3, 4, 2, 1, 2, 1, 3, 1, 1, 4, 1, 1, 1, 2, 2, 1, 2, 1, 1, 1, 2, 1, 3, 1, 1, 1, 3, 1, 2, 1, 1, 1, 3, 1, 1, 1, 1, 1, 1, 1, 2, 2, 3, 1, 1, 2, 2, 1, 3, 2, 2, 1, 1, 1, 3, 2, 2, 2, 2, 2, 3, 2, 2, 1, 2, 1, 1, 3, 1, 2, 4, 1, 1, 2, 1, 1, 1, 1, 1, 2, 2, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 3, 2, 1, 2, 1, 2, 1, 2, 2, 1, 2, 2, 1, 2, 1, 1, 3, 3, 1, 2, 3, 2, 2, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 3, 1, 1, 1, 1, 1, 2, 3, 1, 1, 2, 2, 2, 2, 1, 1, 1, 1, 2, 3, 1, 2, 3, 2, 1, 1, 1, 1, 2, 2, 1, 2, 1, 1, 1, 2, 3, 2, 3, 1, 1, 1, 3, 1, 2, 2, 2, 3, 2, 1, 1, 3, 2, 1, 1, 1, 2, 1, 1, 1, 3, 1, 1, 1, 2, 1, 2]


In [15]:
len(code_symbols)

256

In [17]:
print(src_symbols)

[0 0 1 1 0 1 0 1 0 0 0 0 0 1 0 0 1 0 1 0 1 0 1 1 0 1 1 0 0 0 1 1 1 1 0 0 1
 1 1 1 0 0 1 1 1 1 0 1 0 1 0 0 0 1 1 0 0 1 0 1 0 1 0 0 0 0 0 1 1 1 0 0 1 0
 0 1 1 1 1 1 0 0 0 0 0 0 1 1 1 1 1 0 0 0 1 0 1 0 1 0 1 0 1 1 0 0 1 1 0 1 0
 0 1 1 1 1 0 1 0 1 1 0 1 1 1 1 0 0 1 0 0 0 0 1 0 0 1 1 0 0 0 0 0 1 0 0 0 0
 0 1 1 1 1 0 1 0 1 1 0 1 0 0 1 1 0 1 1 0 0 1 0 0 1 0 1 1 1 0 0 0 1 0 1 0 0
 0 0 0 1 0 1 1 1 1 1 0 1 0 0 1 0 1 1 0 0 0 1 0 0 1 1 0 1 1 1 1 1 0 0 1 1 1
 1 0 1 0 1 1 1 0 0 0 1 1 0 1 1 0 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 0 1 0 0 1
 1 1 1 0 1 1 1 0 1 1 0 0 0 1 0 1 1 0 0 1 1 0 0 0 0 0 1 1 1 0 1 0 1 0 1 0 1
 1 0 0 0 1 1 1 0 1 1 0 1 1 1 1 0 0 1 0 1 0 0 1 1 0 0 1 1 1 0 1 0 1 1 0 0 1
 0 1 0 1 1 1 0 1 0 0 0 1 0 0 0 0 1 0 0 1 0 0 0 0 0 1 1 1 1 1 1 1 0 1 1 1 1
 0 0]


In [20]:

decoded_bits = ccdm.decode(code_symbols, n_i, num_info_bits)
print(decoded_bits)


[0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 

In [21]:
len(decoded_bits)

372

In [24]:
np_src_symbols = np.array(src_symbols)
np_dec_bits = np.array(decoded_bits)

In [25]:
np.array_equal(np_src_symbols, np_dec_bits)

True

### Smaller example

In [4]:
src_symbols = [0, 1, 0, 1, 1, 0]  # arbitrary
n = 3
n_i = [1, 1, 1]  # three output symbols, each one of symbol indices {1,2,3}

In [5]:
code_symbols = ccdm.encode(src_symbols, n, n_i)

In [6]:
print(code_symbols)

[2, 1, 3]
